### ISSUE TITLE
Request 

### ISSUE THREAD

**Issue by justanotherdudeoninternet** [Gerardufoin/FreeKiss#1]
hi i really like your extension but i don't use chrome can u please port this extension for firefox or create a script for violentmonkey  i am using legacy firefox plzzz

**Comment by Gerardufoin** [comment]
Hey, thanks for your interest in FreeKiss.

I thought about adapting the extension for Firefox at some point but put the idea aside at the time as I didn't know if people would be interested in FreeKiss.

I don't know much about extensions on Firefox (I very rarely use it), I'll look into it next week and see what I can do.

Once I know more about it, I'll estimate how long it will take me to adapt FreeKiss for Firefox.

Hopefully you'll soon be able to use it on Firefox as well :)

**Comment by Gerardufoin** [comment]
Hey there,

Ran into some compatibility issues with Firefox, but it's done. You can find the extension here: https://addons.mozilla.org/en-US/firefox/addon/freekiss.

Did some testing and everything seems to be ok, but let me know if you run into some problems :)
