### ISSUE TITLE
 [Request] Sync freekiss with kissmanga folders

### ISSUE THREAD

**Issue by Useless-Panda** [Gerardufoin/FreeKiss#4]
I wanted to make a feature request.
can you make it work with kissmanga's folders.

**Comment by Gerardufoin** [comment]
Hi, sorry for coming back to you this late, had a few life related issues and things have been a bit difficult for me those last few months.

This is one of the feature I would have liked to implement on FreeKiss a few months back, but it means reworking a good part of how the managers work and right now I don't have the drive to do it (I am not reading as much mangas as before).

I'll leave this issue open and will definitely go back to it if I start reading more again, but I can't promise you anything.

**Comment by ghost** [comment]
Hey, No problem, i hope things get better for you.

**Comment by Useless-Panda** [comment]
Kissmanga Is Dead
